name: Local Config
version: 1.0.0
schema: v1
models:
  - name: GLM4.7 (NVIDIA)
    provider: openai
    model: z-ai/glm4.7
    apiKey: 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
    apiBase: https://integrate.api.nvidia.com/v1

  - name: Qwen3.5 (NVIDIA)
    provider: openai
    model: qwen/qwen3-coder-480b-a35b-instruct
    apiKey: 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
    apiBase: https://integrate.api.nvidia.com/v1
